image: node:9.11.1
cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  script:
  - CI=false npm run-script build
  - rm -rf public
  - mv build public

  artifacts:
    paths:
      - public

  only:
    - master
